apiVersion: v2
name: traccar
description: A Helm chart for Traccar GPS Server
type: application
version: 1.4.0
appVersion: "5.6"
dependencies:
  - name: mysql
    version: 9.4.8
    repository: https://charts.bitnami.com/bitnami
    condition: mysql.enabled
maintainers:
  - email: laszlo.kondas@gmail.com
    name: kondas
