apiVersion: v2
name: traccar
description: A Helm chart for Traccar GPS Server
type: application
version: 1.2.0
appVersion: "4.13"
dependencies:
  - name: mysql
    version: 9.1.2
    repository: https://charts.bitnami.com/bitnami
    condition: mysql.enabled
maintainers:
  - email: laszlo.kondas@gmail.com
    name: kondas
