{{- $fullName := include "traccar.fullname" . -}}
{{- $externalfullname := printf "external-%s" $fullName -}}

apiVersion: v1
kind: Service
metadata:
  name: {{ $fullName }}
  labels:
    {{- include "traccar.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "traccar.selectorLabels" . | nindent 4 }}
---
{{- if .Values.externalService.enabled -}}

apiVersion: v1
kind: Service
metadata:
  name: {{ $externalfullname }}
  labels:
    {{- include "traccar.labels" . | nindent 4 }}
spec:
  type: {{ .Values.externalService.type }}
{{- if .Values.externalService.loadBalancerIP }}
  loadBalancerIP: {{ .Values.externalService.loadBalancerIP }}
{{- end }}
{{- if .Values.externalService.loadBalancerSourceRanges }}
  loadBalancerSourceRanges: {{ toYaml .Values.externalService.loadBalancerSourceRanges | nindent 4 }}
{{- end }}
  ports:
    {{- toYaml .Values.externalService.protocolPorts | nindent 4 }}
  selector:
    {{- include "traccar.selectorLabels" . | nindent 4 }}
{{- end }}
