on:
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

permissions: write-all

name: Renovate

jobs:
  renovate:
    name: Renovate

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Run Renovate
        uses: docker://ghcr.io/renovatebot/renovate:latest
        env:
          RENOVATE_REPOSITORIES: ${{ github.repository }}
          RENOVATE_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          RENOVATE_AUTOMERGE: false
